### ISSUE TITLE
Enhancement Suggestion: Exclude Specific File Types to Maintain Telescope Prompt(or others) Functionality

### ISSUE THREAD

**Issue by yongtenglei** [ddl004/poop.nvim#4]
Hey,

Thanks for this legendary plugin! Haha, I've enjoyed using it alongside my workflow.

I've noticed a potential issue where the current implementation might interfere with the normal operation of the Telescope prompt in "i" mode; it may break Telescope and then Eject emojis. To address this, I would like to suggest an enhancement: adding a check to exclude certain file types, specifically those used by the Telescope prompt.

Here’s a sample snippet for illustration using lazy.nvim:

```lua
return {
  "ddl004/poop.nvim",
  config = function()
    -- Function to check if the current file type is excluded
    -- Hint: use ":set filetype?" to find the filetype
    local function is_fts_excluded(buf_ft, excluded_fts)
      for _, ft in ipairs(excluded_fts) do
        if buf_ft == ft then
          return true
        end
      end
      return false
    end

    -- Customized settings
    vim.g.eject_speed = 30
    local emojis = { "💩", "👻", "🐙", "⚡️" }
    local period = 5

    vim.on_key(function(key)
      local excluded_fts = {
        "TelescopePrompt",
        -- more filetypes
      }

      local mode = vim.api.nvim_get_mode().mode
      local buf_ft = vim.api.nvim_buf_get_option(0, "filetype")

      if mode ~= "i" or is_fts_excluded(buf_ft, excluded_fts) then
        return
      end

      vim.schedule_wrap(function()
        local left = emojis[math.random(1, #emojis)]
        local right = emojis[math.random(1, #emojis)]
        local should_eject = math.random(1, period) == 1

        if should_eject then
          vim.cmd.Eject(left, right)
        end
      end)()
    end, nil)
  end,
}
```

Thanks for this plugin again, very interesting.

**Comment by ddl004** [comment]
Hey, thanks for the feedback! I had actually run into this issue in development while using the stable release of neovim, but didn't run into it on v0.10, so I had stopped looking into a fix. 
I went ahead and added your suggestion to the README in https://github.com/ddl004/poop.nvim/pull/5. Thank you for figuring out how to exclude telescope windows!
